package com.myspace.demo;


import java.util.ArrayList;
import java.util.List;
    
/**
 * This class was automatically generated by the data modeler tool.
 */

public class createSessionRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "displayname")
	private java.lang.String displayname;
	@org.kie.api.definition.type.Label(value = "documents")
	public java.util.List<com.myspace.demo.document> documents;
	@org.kie.api.definition.type.Label(value = "foruser")
	private java.lang.String foruser;
	@org.kie.api.definition.type.Label(value = "uploadEnabled")
	private java.lang.String uploadEnabled;

	public createSessionRequest() {
	}

	public java.lang.String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(java.lang.String displayname) {
		this.displayname = displayname;
	}

	public java.util.List<com.myspace.demo.document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(java.util.List<com.myspace.demo.document> documents) {
		this.documents = documents;
	}
	

	public java.lang.String getForuser() {
		return this.foruser;
	}

	public void setForuser(java.lang.String foruser) {
		this.foruser = foruser;
	}

	public java.lang.String getUploadEnabled() {
		return this.uploadEnabled;
	}

	public void setUploadEnabled(java.lang.String uploadEnabled) {
		this.uploadEnabled = uploadEnabled;
	}

	public createSessionRequest(java.lang.String displayname,
			java.util.List<com.myspace.demo.document> documents,
			java.lang.String foruser, java.lang.String uploadEnabled) {
		this.displayname = displayname;
		this.documents = documents;
		this.foruser = foruser;
		this.uploadEnabled = uploadEnabled;
	}

}