package com.myspace.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class createPDFData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label("lastName")
	private java.lang.String lastName;

	@org.kie.api.definition.type.Label(value = "phoneNumber")
	private java.lang.String phoneNumber;

	public createPDFData() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public createPDFData(java.lang.String firstName, java.lang.String lastName,
			java.lang.String phoneNumber) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
	}

}