package com.myspace.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class uploadDocumentResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "success")
	private java.lang.String success;
	@org.kie.api.definition.type.Label(value = "error")
	private java.lang.Integer error;
	@org.kie.api.definition.type.Label(value = "message")
	private java.lang.String message;
	@org.kie.api.definition.type.Label(value = "docid")
	private java.lang.String docid;

	public uploadDocumentResponse() {
	}

	public java.lang.String getSuccess() {
		return this.success;
	}

	public void setSuccess(java.lang.String success) {
		this.success = success;
	}

	public java.lang.Integer getError() {
		return this.error;
	}

	public void setError(java.lang.Integer error) {
		this.error = error;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getDocid() {
		return this.docid;
	}

	public void setDocid(java.lang.String docid) {
		this.docid = docid;
	}

	public uploadDocumentResponse(java.lang.String success,
			java.lang.Integer error, java.lang.String message,
			java.lang.String docid) {
		this.success = success;
		this.error = error;
		this.message = message;
		this.docid = docid;
	}

}